---

- name: medios_bot
  hosts: all
  become: yes
  
  vars:
    stack: medios_bot
    
  tasks:
      
    # ANSIBLE requirements        
    - name: ensure python is present
      apt: name=python state=present
      tags: installation

    - name: ensure pip is present
      easy_install:
        name: pip
        state: present
      tags: installation

    # ansible-docker requirements
    - name: python package docker-py is deprecated
      pip:
        name: docker-py
        state: absent
      tags: installation

    - name: ensure python package docker is present
      pip:
        name: docker
        state: present
      tags: installation

    - name: ensure python package docker-compose is present
      pip:
        name: docker-compose
        state: present
      tags: installation

    # TODO additional dependencies?
    # apt:name=libmariadbclient-dev
  
    # DOCKER images

    - name: pull bot
      docker_image:
        name: numericalatina/medios_bot
        force: yes # latest
  
    - name: pull mariadb
      docker_image:
        name: mariadb
      tags: installation

    # SETTINGS
    - file: dest="{{ compose_path }}/ml" state="directory"

    - name: settigns decrypted
      copy: src="{{ playbook_dir }}/group_vars/numerica/settings.py" dest="{{ compose_path }}/ml/settings.py"
  
    # ORCHESTRATION
  
    - name: template compose
      template: 
        dest: "{{ compose_path }}/ml/medios_bot.yml"
        src: docker-compose.yml

    - name: update stack
      command: "docker stack deploy -c {{ compose_path }}/ml/medios_bot.yml {{stack}}"

