---

- name: medios_bot
  hosts: all
  become: yes
  
  vars:
    stack: medios_bot
    
  tasks:
      
    # ANSIBLE requirements        
    - name: ensure python is present
      apt: name=python state=present
      tags: installation

    - name: ensure pip is present
      easy_install:
        name: pip
        state: present
      tags: installation

    # ansible-docker requirements
    - name: python package docker-py is deprecated
      pip:
        name: docker-py
        state: absent
      tags: installation

    - name: ensure python package docker is present
      pip:
        name: docker
        state: present
      tags: installation

    - name: ensure python package docker-compose is present
      pip:
        name: docker-compose
        state: present
      tags: installation

    # TODO additional dependencies?
    # apt:name=libmariadbclient-dev
  
    # DOCKER images

    - name: pull imagen del bot
      docker_image:
        name: numericalatina/medios_bot
        force: yes # pull
  
    - name: pull imagen mariadb
      docker_image:
        name: mariadb
      tags: installation
  
    # ORCHESTRATION
  
    - name: copiar docker-compose.yml
      template: 
        dest: "~/medios_bot.yml"
        src: docker-compose.yml

    - name: actualizar stack de docker
      command: "docker stack deploy -c ~/medios_bot.yml {{stack}}"

