version: "3"
services:

  bot:
    image: numericalatina/medios_bot
    restart: always
    networks:
      - bot_db
    volumes:
      - "{{ compose_path }}/ml/settings.py:/app/medios_libres/medios_libres/settings.py"

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - bot_db_data:/var/lib/mysql
    networks:
      - bot_db
    environment:
      MYSQL_ROOT_PASSWORD: "{{ vault_MYSQL_ROOT_PASSWORD }}"
      MYSQL_DATABASE: "{{ vault_MYSQL_DATABASE }}"
      MYSQL_USER: "{{ vault_MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ vault_MYSQL_PASSWORD }}"

  wordpress:
    image: wordpress
    restart: always
    volumes:
      - wp_bot_vol:/var/www/html
    networks:
      - bot_db
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: "{{ vault_MYSQL_DATABASE }}"
      WORDPRESS_DB_USER: "{{ vault_MYSQL_USER }}"
      WORDPRESS_DB_PASSWORD: "{{ vault_MYSQL_PASSWORD }}"
    ports:
      - "8888:80"

networks:
  bot_db:

volumes:
  wp_bot_vol:
  bot_db_data:
