version: "3"
services:
  bot:
    image: numericalatina/medios_bot
    deploy:
      replicas: 1
    ports:
      - "8888:8000"
    networks:
      - red
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: laSextaDeclaracion
    networks:
      - red
networks:
  red:
