# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_libres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('longi', models.FloatField()),
                ('usuario', models.CharField(max_length=50)),
                ('tiempo', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
