# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_libres', '0003_wpcommentmeta_wpcomments_wplinks_wppostmeta_wpposts_wptermmeta_wptermrelationships_wpterms_wptermtax'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpUsers',
            fields=[
                ('id', models.BigAutoField(db_column=b'ID', primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=60)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_nicename', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_url', models.CharField(max_length=100)),
                ('user_registered', models.DateTimeField()),
                ('user_activation_key', models.CharField(max_length=255)),
                ('user_status', models.IntegerField()),
                ('display_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'wp_users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Texto',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
